export enum DataPaths {
  CARTOONS_ABOUT_US = "cartoons/about-us",
  CARTOONS_ARCHIVE = "cartoons/archive",
  CARTOONS_TEAM = "cartoons/team",
  CONTACT_US = "contact-us",
  ELECTIONS = "elections",
  GET_INVOLVED_CLUBS_DATA = "get-involved/clubs",
  GET_INVOLVED_COMMUNITY_DATA = "get-involved/community",
  GET_INVOLVED_COUNCIL_DATA = "get-involved/council",
  GET_INVOLVED_VOLUNTEER = "get-involved/volunteer",
  GET_INVOLVED_VOLUNTEER_APPLICATION = "get-involved/volunteer-application",
  HOME = "home",
  INVENTORY = "inventory",
  RESOURCES_BUDGETS = "resources/budgets",
  RESOURCES_DISCORD_ACCESS = "resources/discord-access",
  RESOURCES_FORMS = "resources/forms",
  RESOURCES_IMPORTANT_LINKS = "resources/important-links",
  RESOURCES_MENTAL_WELLNESS = "resources/mental-wellness",
  RESOURCES_MEETINGS = "resources/meetings",
  RESOURCES_POLICIES_AND_BYLAWS = "resources/policies-and-bylaws",
  SHARED_EXECS = "shared/execs",
  SHARED_FOOTER = "shared/footer",
  SERVICES_MATHSOC_OFFICE = "services/mathsoc-office",
  SERVICES_STUDENT_SERVICES = "services/student-services",
}
