export enum DataPaths {
  CARTOONS_ABOUT_US = "cartoons/about-us",
  CONTACT_US = "contact-us",
  DOCUMENTS_BUDGETS = "documents/budgets",
  ELECTIONS = "elections",
  HOME = "home",
  GET_INVOLVED_VOLUNTEER = "get-involved/volunteer",
  GET_INVOLVED_VOLUNTEER_APPLICATION = "get-involved/volunteer-application",
  CLUBS_DATA = "get-involved/clubs",
  COMMUNITY_DATA = "get-involved/community",
  COUNCIL_DATA = "get-involved/council",
  RESOUCES_MENTAL_WELLNESS = "resources/mental-wellness",
  RESOURCES_CHEQUE_REQUESTS = "resources/cheque-requests",
  RESOURCES_DISCORD_ACCESS = "resources/discord-access",
  STUDENT_SERVICES = "services/student-services",
  SERVICES_MATHSOC_OFFICE = "services/mathsoc-office",
  SHARED_FOOTER = "shared/footer",
  SHARED_EXECS = "shared/execs",
}
